{
  "hash": "009132b48c1a81b50d990dee9cbceff3",
  "result": {
    "engine": "jupyter",
    "markdown": "---\njupyter: ds\ntitle: \"Air Quality (Classification Case)\"\nauthor: \"Christoffer Boye Tvedte\"\nformat:\n  html:\n    toc: true\n    number-sections: true\n    code-fold: true\n    theme: cosmo\nexecute:\n  warning: false\n  message: false\n  echo: true\n---\n\n\n## Executive Summary\n\nThis mini-case builds a predictive model for classifying air quality levels (Good, Moderate, Poor, Hazardous) based on pollutant concentrations and environmental factors.\n\n- **Best-performing model (test split):** Tuned HistGradientBoostingClassifier  \n- **Performance (test split):** Macro F1-score **0.215**, Log Loss **1.322**, Accuracy **39.1%**  \n- **Benchmarks:** Logistic Regression log loss 1.396 (Accuracy 0.208, Macro F1 0.201); Quadratic Logistic Regression log loss 1.407 (Accuracy 0.220, Macro F1 0.216)\n- **Key insight:** PM2.5 and PM10 concentrations are the strongest predictors, while NO2, SO2, and CO provide additional signal. Environmental factors like temperature and humidity contribute marginally.\n- **Practical relevance:** The model enables data-driven air quality monitoring and supports targeted interventions for pollution control.\n\n## Problem Statement\n\nAir quality categories are used to communicate health risk and guide actions such as warnings, traffic restrictions, or industrial mitigation.\nThe objective of this case is to **predict air quality level** from measured pollutant concentrations and contextual variables.\n\nA good solution should:\n\n1. Produce reliable probabilistic predictions (low log loss) and balanced performance across categories (macro F1).\n\n2. Remain interpretable enough to explain which environmental factors are most associated with deteriorating air quality.\n\n## Data\n\nThe data set `pollution.csv` contains the following variables.\n\n| Variable | Description |\n| -------- | ----------- | \n| Temperature (°C)                    | Average temperature of the region. |\n| Humidity (%)                        | Relative humidity recorded in the region. |\n| PM2.5 Concentration (µg/m³)         | Fine particulate matter levels. |\n| PM10 Concentration (µg/m³)          | Coarse particulate matter levels. |\n| NO2 Concentration (ppb)             | Nitrogen dioxide levels. |\n| SO2 Concentration (ppb)             | Sulfur dioxide levels. |\n| CO Concentration (ppm)              | Carbon monoxide levels. |\n| Proximity to Industrial Areas (km)  | Distance to the nearest industrial zone. |\n| Population Density (people/km²)     | Number of people per square kilometer in the region. |\n| Air Quality Levels                  | Quantification of air quality **Target**. |\n\n\n\n### Import and investigate\n\n::: {#de601f4e .cell execution_count=2}\n``` {.python .cell-code}\npollution = pd.read_csv(\"../data/pollution.csv\").dropna()\n\npollution.describe()\n```\n\n::: {.cell-output .cell-output-display execution_count=16}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Temperature</th>\n      <th>Humidity</th>\n      <th>PM2.5</th>\n      <th>PM10</th>\n      <th>NO2</th>\n      <th>SO2</th>\n      <th>CO</th>\n      <th>Proximity_to_Industrial_Areas</th>\n      <th>Population_Density</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>count</th>\n      <td>5000.000000</td>\n      <td>5000.000000</td>\n      <td>5000.000000</td>\n      <td>5000.000000</td>\n      <td>5000.00000</td>\n      <td>5000.000000</td>\n      <td>5000.000000</td>\n      <td>5000.000000</td>\n      <td>5000.000000</td>\n    </tr>\n    <tr>\n      <th>mean</th>\n      <td>25.464580</td>\n      <td>60.068140</td>\n      <td>29.905580</td>\n      <td>40.003700</td>\n      <td>21.00036</td>\n      <td>15.141060</td>\n      <td>0.904314</td>\n      <td>5.031880</td>\n      <td>299.948200</td>\n    </tr>\n    <tr>\n      <th>std</th>\n      <td>5.486219</td>\n      <td>15.044806</td>\n      <td>30.285899</td>\n      <td>30.693124</td>\n      <td>11.30099</td>\n      <td>7.668466</td>\n      <td>0.297840</td>\n      <td>5.010352</td>\n      <td>17.215133</td>\n    </tr>\n    <tr>\n      <th>min</th>\n      <td>3.500000</td>\n      <td>10.000000</td>\n      <td>0.000000</td>\n      <td>-1.400000</td>\n      <td>-13.50000</td>\n      <td>0.000000</td>\n      <td>-0.080000</td>\n      <td>0.000000</td>\n      <td>243.000000</td>\n    </tr>\n    <tr>\n      <th>25%</th>\n      <td>21.800000</td>\n      <td>49.900000</td>\n      <td>8.500000</td>\n      <td>18.900000</td>\n      <td>13.80000</td>\n      <td>9.900000</td>\n      <td>0.700000</td>\n      <td>1.500000</td>\n      <td>288.000000</td>\n    </tr>\n    <tr>\n      <th>50%</th>\n      <td>25.300000</td>\n      <td>60.200000</td>\n      <td>20.600000</td>\n      <td>31.100000</td>\n      <td>20.50000</td>\n      <td>15.100000</td>\n      <td>0.905000</td>\n      <td>3.500000</td>\n      <td>300.000000</td>\n    </tr>\n    <tr>\n      <th>75%</th>\n      <td>28.900000</td>\n      <td>70.100000</td>\n      <td>41.500000</td>\n      <td>51.500000</td>\n      <td>27.50000</td>\n      <td>20.400000</td>\n      <td>1.100000</td>\n      <td>6.900000</td>\n      <td>311.000000</td>\n    </tr>\n    <tr>\n      <th>max</th>\n      <td>46.200000</td>\n      <td>100.000000</td>\n      <td>249.000000</td>\n      <td>256.100000</td>\n      <td>96.40000</td>\n      <td>41.700000</td>\n      <td>2.140000</td>\n      <td>46.300000</td>\n      <td>358.000000</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nSome pollutant measurements contain small negative values (likely measurement noise / data artefacts). Since negative concentrations are not physically meaningful, I will clip values at zero.\n\n::: {#96205b97 .cell execution_count=3}\n``` {.python .cell-code}\npollution[[\"PM2.5\", \"PM10\", \"NO2\", \"SO2\", \"CO\"]] = pollution[[\"PM2.5\", \"PM10\", \"NO2\", \"SO2\", \"CO\"]].clip(lower=0)\npollution.describe()\n```\n\n::: {.cell-output .cell-output-display execution_count=17}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Temperature</th>\n      <th>Humidity</th>\n      <th>PM2.5</th>\n      <th>PM10</th>\n      <th>NO2</th>\n      <th>SO2</th>\n      <th>CO</th>\n      <th>Proximity_to_Industrial_Areas</th>\n      <th>Population_Density</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>count</th>\n      <td>5000.000000</td>\n      <td>5000.000000</td>\n      <td>5000.000000</td>\n      <td>5000.000000</td>\n      <td>5000.000000</td>\n      <td>5000.000000</td>\n      <td>5000.000000</td>\n      <td>5000.000000</td>\n      <td>5000.000000</td>\n    </tr>\n    <tr>\n      <th>mean</th>\n      <td>25.464580</td>\n      <td>60.068140</td>\n      <td>29.905580</td>\n      <td>40.004320</td>\n      <td>21.072720</td>\n      <td>15.141060</td>\n      <td>0.904394</td>\n      <td>5.031880</td>\n      <td>299.948200</td>\n    </tr>\n    <tr>\n      <th>std</th>\n      <td>5.486219</td>\n      <td>15.044806</td>\n      <td>30.285899</td>\n      <td>30.692304</td>\n      <td>11.145492</td>\n      <td>7.668466</td>\n      <td>0.297589</td>\n      <td>5.010352</td>\n      <td>17.215133</td>\n    </tr>\n    <tr>\n      <th>min</th>\n      <td>3.500000</td>\n      <td>10.000000</td>\n      <td>0.000000</td>\n      <td>0.000000</td>\n      <td>0.000000</td>\n      <td>0.000000</td>\n      <td>0.000000</td>\n      <td>0.000000</td>\n      <td>243.000000</td>\n    </tr>\n    <tr>\n      <th>25%</th>\n      <td>21.800000</td>\n      <td>49.900000</td>\n      <td>8.500000</td>\n      <td>18.900000</td>\n      <td>13.800000</td>\n      <td>9.900000</td>\n      <td>0.700000</td>\n      <td>1.500000</td>\n      <td>288.000000</td>\n    </tr>\n    <tr>\n      <th>50%</th>\n      <td>25.300000</td>\n      <td>60.200000</td>\n      <td>20.600000</td>\n      <td>31.100000</td>\n      <td>20.500000</td>\n      <td>15.100000</td>\n      <td>0.905000</td>\n      <td>3.500000</td>\n      <td>300.000000</td>\n    </tr>\n    <tr>\n      <th>75%</th>\n      <td>28.900000</td>\n      <td>70.100000</td>\n      <td>41.500000</td>\n      <td>51.500000</td>\n      <td>27.500000</td>\n      <td>20.400000</td>\n      <td>1.100000</td>\n      <td>6.900000</td>\n      <td>311.000000</td>\n    </tr>\n    <tr>\n      <th>max</th>\n      <td>46.200000</td>\n      <td>100.000000</td>\n      <td>249.000000</td>\n      <td>256.100000</td>\n      <td>96.400000</td>\n      <td>41.700000</td>\n      <td>2.140000</td>\n      <td>46.300000</td>\n      <td>358.000000</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n### Target & features\n\n::: {#c8020ffd .cell execution_count=4}\n``` {.python .cell-code}\ntarget = \"Air Quality\"\nX = pollution.drop([\"Air Quality\"], axis=1)\ny = pollution[target]\n\nlabel_encoder = LabelEncoder()\ny_encoded = label_encoder.fit_transform(y)\n```\n:::\n\n\n### Inspect \n\n::: {#cell-fig-target-dist .cell fig-height='4' fig-width='7' execution_count=5}\n``` {.python .cell-code}\ntarget_counts = y.value_counts()\n\nplt.figure(figsize=(10, 6))\ntarget_counts.plot(kind='bar', color='skyblue')\nplt.title('Distribution of Target Categories (Air Quality)')\nplt.xlabel('Air Quality Categories')\nplt.ylabel('Count')\nplt.xticks(rotation=45)\nplt.show()\n\npercentages = (target_counts / len(y)) * 100\n\nprint(target_counts)\nprint(\"\\nPercentage distribution:\\n\", percentages)\n```\n\n::: {.cell-output .cell-output-display}\n![Distribution of target categories (Air Quality).](02_classification_airquality_files/figure-html/fig-target-dist-output-1.png){#fig-target-dist}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nAir Quality\nGood         2000\nModerate     1500\nPoor         1000\nHazardous     500\nName: count, dtype: int64\n\nPercentage distribution:\n Air Quality\nGood         40.0\nModerate     30.0\nPoor         20.0\nHazardous    10.0\nName: count, dtype: float64\n```\n:::\n:::\n\n\n::: {#cell-fig-kde-distributions .cell fig-height='10' fig-width='10' execution_count=6}\n``` {.python .cell-code}\norder = [\"Good\", \"Moderate\", \"Poor\", \"Hazardous\"]\nfeatures = [\"PM2.5\", \"PM10\", \"NO2\", \"SO2\", \"CO\"]\n\nfig, axes = plt.subplots(len(features), 1, figsize=(10, 12), sharex=False)\n\nfor ax, col in zip(axes, features):\n    sns.kdeplot(\n        data=pollution,\n        x=col,\n        hue=\"Air Quality\",\n        hue_order=order,\n        common_norm=False,\n        ax=ax\n    )\n    ax.set_title(f\"{col} distribution by Air Quality\")\n    ax.legend_.remove()  \n\nhandles, labels = axes[0].get_legend_handles_labels()\nfig.legend(handles, labels, loc=\"upper right\", title=\"Air Quality Categories\", labels=order)\n\nfor ax, col in zip(axes, features):\n    ax.set_ylabel(f\"Density ({col})\")\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![KDE distributions of key pollutants by air quality category.](02_classification_airquality_files/figure-html/fig-kde-distributions-output-1.png){#fig-kde-distributions}\n:::\n:::\n\n\n1. Target imbalance:\n\n   By examening @fig-target-dist we can see that the target variable is partially imbalanced. The category \"Good air quality\" accounts for 40% of the data, while \"Hazardous air quality\" accounts for only 10%. Although the difference is not a very high, it may still lead to the classification models to favor the majority classes. This potential bias could impact the models ability to accurately classify the minority classes, especially if they represent critical conditions. \n\n2. Pairplot patterns:\n\n    For visualization, I focus the KDE plots on pollutant concentration variables (PM2.5, PM10, NO2, SO2, CO) because they are the most direct drivers of air quality categories and yield interpretable distribution comparisons across classes. All available features (including temperature, humidity, proximity to industrial areas, and population density) are still included in model training and are later evaluated using model-based feature importance.\n    \n    The KDE plots in @fig-kde-distributions show substantial overlap between air quality categories for most variables. PM2.5 and PM10 are strongly right-skewed and exhibit slightly different tails across categories, suggesting they may carry more signal than the other pollutants. NO2, SO2, and CO show highly overlapping distributions, indicating limited separability when considered individually. Overall, the overlap suggests that robust performance will likely require combining multiple predictors and capturing interactions, which motivates comparing linear and non-linear classifiers and using model-based feature importance later.\n \n\n   \n\n\n## Modeling\n\n::: {#ae5267c0 .cell execution_count=7}\n``` {.python .cell-code}\nlabel_encoder = LabelEncoder()\ny_encoded = label_encoder.fit_transform(y)\n\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded\n)\n\nclass_names = label_encoder.classes_\nclass_names\n```\n\n::: {.cell-output .cell-output-display execution_count=21}\n```\narray(['Good', 'Hazardous', 'Moderate', 'Poor'], dtype=object)\n```\n:::\n:::\n\n\n::: {#bcf74d56 .cell execution_count=8}\n``` {.python .cell-code}\nbaseline = DummyClassifier(strategy=\"most_frequent\", random_state=42)\nbaseline.fit(X_train, y_train)\n\nbase_pred = baseline.predict(X_test)\nbase_proba = baseline.predict_proba(X_test)\n\nbaseline_metrics = {\n    \"Model\": \"Baseline (most frequent)\",\n    \"LogLoss\": log_loss(y_test, base_proba),\n    \"MacroF1\": f1_score(y_test, base_pred, average=\"macro\"),\n    \"Accuracy\": accuracy_score(y_test, base_pred),\n}\nbaseline_metrics\n```\n\n::: {.cell-output .cell-output-display execution_count=22}\n```\n{'Model': 'Baseline (most frequent)',\n 'LogLoss': 21.626192033470286,\n 'MacroF1': 0.14285714285714285,\n 'Accuracy': 0.4}\n```\n:::\n:::\n\n\n### Logistic regression\n\n::: {#191d1ea4 .cell execution_count=9}\n``` {.python .cell-code}\nlogreg = Pipeline([\n    (\"scaler\", StandardScaler()),\n    (\"clf\", LogisticRegression(max_iter=5000, class_weight=\"balanced\", random_state=42))\n])\n\nlogreg.fit(X_train, y_train)\npred = logreg.predict(X_test)\nproba = logreg.predict_proba(X_test)\n\nlogreg_metrics = {\n    \"Model\": \"Logistic Regression\",\n    \"LogLoss\": log_loss(y_test, proba),\n    \"MacroF1\": f1_score(y_test, pred, average=\"macro\"),\n    \"Accuracy\": accuracy_score(y_test, pred),\n}\nlogreg_metrics\n```\n\n::: {.cell-output .cell-output-display execution_count=23}\n```\n{'Model': 'Logistic Regression',\n 'LogLoss': 1.3961318133168998,\n 'MacroF1': 0.20090680690563487,\n 'Accuracy': 0.208}\n```\n:::\n:::\n\n\nThe baseline model (most-frequent class) provides a minimum performance reference. Since it always predicts the same class, it can achieve a relatively high accuracy in an imbalanced dataset, but it does not learn any relationship between the features and the target. In this case, the baseline reaches an accuracy of 0.40 and a macro F1 of 0.143. However, its log loss is 21.63, which is extremely poor. This is expected because the baseline assigns almost all probability mass to a single class, meaning the model is effectively “certain” even when the true label belongs to a different category—log loss penalizes such overconfident misclassification heavily in multiclass settings.\n\nThe log loss measures how well a model predicts class probabilities. It penalizes confident wrong predictions more strongly, so lower log loss is better. The Logistic Regression model achieves a log loss of 1.396, which is a major improvement over the baseline (21.63). This indicates that the model produces more meaningful probability estimates and captures real signal from the predictors, even if classification accuracy remains low.\n\nThe accuracy score measures the proportion of correctly predicted labels. Logistic Regression achieves an accuracy of 0.208, which is lower than the baseline accuracy (0.40). This suggests that the linear decision boundaries of Logistic Regression may not be sufficient to outperform a majority-class strategy on raw label correctness, especially given overlap between class distributions observed in the EDA.\n\nTo account for class imbalance, I also report macro F1, which weighs all classes equally. Logistic Regression achieves a macro F1 of 0.201, improving over the baseline (0.143). This indicates better balanced performance across categories, even though the model still struggles overall.\n\nIn summary, Logistic Regression produces substantially better probability calibration (log loss) and better class-balanced performance (macro F1), but it does not improve raw accuracy relative to a majority-class baseline. In the next step, I test more flexible non-linear models to better capture interactions and improve separation between air quality categories.\n\n\n\n### Quadratic logistic regression\n\n::: {#16849ef6 .cell execution_count=10}\n``` {.python .cell-code}\npoly_logreg = Pipeline([\n    (\"poly\", PolynomialFeatures(degree=2, include_bias=False)),\n    (\"scaler\", StandardScaler()),\n    (\"clf\", LogisticRegression(max_iter=5000, class_weight=\"balanced\", random_state=42))\n])\n\npoly_logreg.fit(X_train, y_train)\npred = poly_logreg.predict(X_test)\nproba = poly_logreg.predict_proba(X_test)\n\npoly_metrics = {\n    \"Model\": \"Quadratic LogReg (poly deg=2)\",\n    \"LogLoss\": log_loss(y_test, proba),\n    \"MacroF1\": f1_score(y_test, pred, average=\"macro\"),\n    \"Accuracy\": accuracy_score(y_test, pred),\n}\npoly_metrics\n```\n\n::: {.cell-output .cell-output-display execution_count=24}\n```\n{'Model': 'Quadratic LogReg (poly deg=2)',\n 'LogLoss': 1.4073081908880127,\n 'MacroF1': 0.21580139321998046,\n 'Accuracy': 0.22}\n```\n:::\n:::\n\n\nAdding polynomial (degree-2) features slightly improves class-balanced performance (macro F1 increases from 0.201 to 0.216 and accuracy increases from 0.208 to 0.22). However, log loss becomes slightly worse (1.396 to 1.407), indicating that probability calibration does not improve. To check whether these differences are robust, I evaluate both models using stratified cross-validation on the training set.\n\n\n### Boosting\n\n**Train & Evaluate**\n\n::: {#a840ea70 .cell execution_count=11}\n``` {.python .cell-code}\nboost = HistGradientBoostingClassifier(random_state=42)\nboost.fit(X_train, y_train)\n\npred = boost.predict(X_test)\nproba = boost.predict_proba(X_test)\n\nboost_metrics = {\n    \"Model\": \"HistGradientBoosting\",\n    \"LogLoss\": log_loss(y_test, proba),\n    \"MacroF1\": f1_score(y_test, pred, average=\"macro\"),\n    \"Accuracy\": accuracy_score(y_test, pred),\n}\nboost_metrics\n```\n\n::: {.cell-output .cell-output-display execution_count=25}\n```\n{'Model': 'HistGradientBoosting',\n 'LogLoss': 1.439946392696233,\n 'MacroF1': 0.25266814951838945,\n 'Accuracy': 0.354}\n```\n:::\n:::\n\n\n**Permutation importance**\n\n::: {#fig-importance .cell execution_count=12}\n``` {.python .cell-code}\nperm = permutation_importance(\n    boost, X_test, y_test, n_repeats=10, random_state=42, scoring=\"neg_log_loss\"\n)\n\nimp = pd.Series(perm.importances_mean, index=X.columns).sort_values(ascending=False).head(10)\n\nplt.figure()\nimp.sort_values().plot(kind=\"barh\")\nplt.title(\"Permutation importance (Boosting, test set) — Top 10\")\nplt.xlabel(\"Importance (decrease in performance when permuted)\")\nplt.ylabel(\"\")\nplt.show()\n\nimp\n```\n\n::: {.cell-output .cell-output-display}\n![Permutation importance of features for the boosting model (test set).](02_classification_airquality_files/figure-html/fig-importance-output-1.png){#fig-importance-1}\n:::\n\n::: {#fig-importance-2 .cell-output .cell-output-display execution_count=26}\n```\nPM2.5                            0.015945\nPM10                             0.009462\nCO                               0.003099\nPopulation_Density               0.000348\nSO2                             -0.003213\nProximity_to_Industrial_Areas   -0.004093\nTemperature                     -0.004874\nNO2                             -0.006953\nHumidity                        -0.010414\ndtype: float64\n```\n:::\n:::\n\n\nBoosted score:\n   The boosting classifier performs better than the logistic regression models on the test set, achieving higher accuracy (0.354) and higher macro F1 (0.253). However, the log loss (1.440) is not improved compared to logistic regression, suggesting that while boosting predicts labels more effectively, its probability estimates are not clearly better calibrated.\nImportance plot:\n   In the permutation importance plot @fig-importance, PM2.5 and PM10 stand out as the most influential predictors. Several other features have near-zero importance, and some show slightly negative values. Negative permutation importance can occur due to sampling noise and indicates that permuting the feature does not consistently harm performance. Overall, the plot suggests that the model relies primarily on particulate matter measures, while variables such as Population_Density contribute little in this setting.\nConclusion:\n   Overall, boosting provides stronger class-balanced classification performance (macro F1) and improved accuracy relative to logistic regression, which indicates that non-linear modelling adds value for label prediction. At the same time, the probability quality (log loss) does not improve, so logistic regression may remain preferable if well-calibrated probabilities are the main goal. A reasonable next step is to tune boosting hyperparameters and consider simplifying the feature set by removing consistently low-importance variables to reduce noise and improve stability. \n\n\n### Tuning boosting hyperparameters\n\n::: {#b80577e2 .cell execution_count=13}\n``` {.python .cell-code}\nparam_grid = {\n    \"learning_rate\": [0.05, 0.1],\n    \"max_depth\": [3, None],\n    \"max_iter\": [200, 400],\n}\n\ncv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)\n\ngs = GridSearchCV(\n    HistGradientBoostingClassifier(random_state=42),\n    param_grid=param_grid,\n    scoring=\"neg_log_loss\",\n    cv=cv,\n    n_jobs=-1\n)\ngs.fit(X_train, y_train)\n\nbest_boost = gs.best_estimator_\ngs.best_params_, -gs.best_score_\n\npred = best_boost.predict(X_test)\nproba = best_boost.predict_proba(X_test)\n\nbest_boost_metrics = {\n    \"Model\": \"HistGradientBoosting\",\n    \"LogLoss\": log_loss(y_test, proba),\n    \"MacroF1\": f1_score(y_test, pred, average=\"macro\"),\n    \"Accuracy\": accuracy_score(y_test, pred),\n}\nbest_boost_metrics\n```\n\n::: {.cell-output .cell-output-display execution_count=27}\n```\n{'Model': 'HistGradientBoosting',\n 'LogLoss': 1.3215838187111557,\n 'MacroF1': 0.21541108974737294,\n 'Accuracy': 0.391}\n```\n:::\n:::\n\n\n## Results\n\n::: {#tbl-final-results .cell tbl-cap='Model comparison on the test set.' execution_count=14}\n``` {.python .cell-code}\nresults_df = pd.DataFrame([\n    baseline_metrics,\n    logreg_metrics,\n    poly_metrics,\n    best_boost_metrics, \n])\n\nresults_df = results_df.rename(columns={\n    \"LogLoss\": \"Test_LogLoss\",\n    \"MacroF1\": \"Test_MacroF1\",\n    \"Accuracy\": \"Test_Accuracy\"\n})\n\nresults_df.sort_values(\"Test_LogLoss\").style.format({\n    \"Test_LogLoss\": \"{:.3f}\",\n    \"Test_MacroF1\": \"{:.3f}\",\n    \"Test_Accuracy\": \"{:.3f}\",\n    \"CV_LogLoss\": \"{:.3f}\" if \"CV_LogLoss\" in results_df.columns else \"{:.3f}\"\n})\n```\n\n::: {.cell-output .cell-output-display execution_count=28}\n```{=html}\n<style type=\"text/css\">\n</style>\n<table id=\"T_ec174\">\n  <thead>\n    <tr>\n      <th class=\"blank level0\" >&nbsp;</th>\n      <th id=\"T_ec174_level0_col0\" class=\"col_heading level0 col0\" >Model</th>\n      <th id=\"T_ec174_level0_col1\" class=\"col_heading level0 col1\" >Test_LogLoss</th>\n      <th id=\"T_ec174_level0_col2\" class=\"col_heading level0 col2\" >Test_MacroF1</th>\n      <th id=\"T_ec174_level0_col3\" class=\"col_heading level0 col3\" >Test_Accuracy</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th id=\"T_ec174_level0_row0\" class=\"row_heading level0 row0\" >3</th>\n      <td id=\"T_ec174_row0_col0\" class=\"data row0 col0\" >HistGradientBoosting</td>\n      <td id=\"T_ec174_row0_col1\" class=\"data row0 col1\" >1.322</td>\n      <td id=\"T_ec174_row0_col2\" class=\"data row0 col2\" >0.215</td>\n      <td id=\"T_ec174_row0_col3\" class=\"data row0 col3\" >0.391</td>\n    </tr>\n    <tr>\n      <th id=\"T_ec174_level0_row1\" class=\"row_heading level0 row1\" >1</th>\n      <td id=\"T_ec174_row1_col0\" class=\"data row1 col0\" >Logistic Regression</td>\n      <td id=\"T_ec174_row1_col1\" class=\"data row1 col1\" >1.396</td>\n      <td id=\"T_ec174_row1_col2\" class=\"data row1 col2\" >0.201</td>\n      <td id=\"T_ec174_row1_col3\" class=\"data row1 col3\" >0.208</td>\n    </tr>\n    <tr>\n      <th id=\"T_ec174_level0_row2\" class=\"row_heading level0 row2\" >2</th>\n      <td id=\"T_ec174_row2_col0\" class=\"data row2 col0\" >Quadratic LogReg (poly deg=2)</td>\n      <td id=\"T_ec174_row2_col1\" class=\"data row2 col1\" >1.407</td>\n      <td id=\"T_ec174_row2_col2\" class=\"data row2 col2\" >0.216</td>\n      <td id=\"T_ec174_row2_col3\" class=\"data row2 col3\" >0.220</td>\n    </tr>\n    <tr>\n      <th id=\"T_ec174_level0_row3\" class=\"row_heading level0 row3\" >0</th>\n      <td id=\"T_ec174_row3_col0\" class=\"data row3 col0\" >Baseline (most frequent)</td>\n      <td id=\"T_ec174_row3_col1\" class=\"data row3 col1\" >21.626</td>\n      <td id=\"T_ec174_row3_col2\" class=\"data row3 col2\" >0.143</td>\n      <td id=\"T_ec174_row3_col3\" class=\"data row3 col3\" >0.400</td>\n    </tr>\n  </tbody>\n</table>\n```\n:::\n:::\n\n\nFinal Comparison\n    Across the evaluated models (Table @tbl-final-results), HistGradientBoosting achieves the best overall performance on the test set with log loss = 1.322 and accuracy = 0.391, indicating improved probability estimates and higher label correctness compared to the linear baselines. Logistic Regression performs notably worse (log loss = 1.396, accuracy = 0.208), suggesting that linear decision boundaries are not sufficient to separate the four air quality categories in this dataset. \n\n    The polynomial logistic regression provides a small improvement in accuracy (0.22 vs 0.208) but does not improve log loss, indicating that while it captures some non-linear interactions, it does not produce better-calibrated probabilities. \n\n    The baseline model (most frequent class) achieves a relatively high accuracy (0.40) due to class imbalance but has very poor log loss (21.63), confirming that it does not learn any meaningful relationships between features and the target.\nConclusion\n    Overall, the tuned boosting model provides the best balance of improved probability estimates (log loss) and better label prediction (accuracy, macro F1), making it the most effective choice for this classification task. The importance analysis also highlights which features are driving predictions, providing insights into the factors influencing air quality categories.\n\n    In a real deployment, I would further validate the boosting model with cross-validation and consider probability calibration (e.g., isotonic regression) if calibrated risk scores are required.\n\n",
    "supporting": [
      "02_classification_airquality_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}